

applyAndroidApplication("com.nu.art.cyborg.demo", "cyborg-demo")

android {
    packagingOptions {
        exclude 'META-INF/*'
    }
}

configurations.all {
    exclude group: 'com.google.guava', module: 'listenablefuture'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}

dependencies {
    implementation(resolveDependency('cyborg-x', 'com.nu-art-software.cyborg', "${NU_ART_VERSION}"))

    implementation(project(':payment-stripe'))
    implementation project(':cyborg-maps')
    implementation project(':google-stt')
    implementation project(':logcat-viewer-android')
    implementation project(':http-module')
    implementation project(':automation')
    implementation 'com.google.auth:google-auth-library-oauth2-http:0.9.0'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation project(':automation-agent')
    androidTestImplementation "androidx.test:runner:1.5.2"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.5.1"
    androidTestImplementation project(':automation-core')
}
