project.ext.namespace = 'com.nu.art.cyborg.logcat'
applyAndroidLibrary()

dependencies {
    implementation project(':cyborg-x')
    implementation "com.google.code.gson:gson:${GSON_VERSION}"
}

if (project.hasProperty("addTask_DeployAndroidArtifactToCentral")) {
    addTask_DeployAndroidArtifactToCentral("com.nu-art-software.cyborg", "nu-art")
}
